name: "Build-Test"
on:
  push:
    branches:
    - master

jobs:
  Build:
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - run: |
      xcodebuild -project TestProjects/Starter/BullsEye/BullsEye.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'
