name: Build-Test
on:
  push

jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        xcodebuild test -project TestProjects/Starter/BullsEye/BullsEye.xcodeproj -scheme BullsEye -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'
