name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Show Information
      run: |
        ls -l
